To run this, press "*Runtime*" and press "*Run all*" on your A100 Google Colab Pro instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your local device, follow [our guide](https://unsloth.ai/docs/get-started/install). This notebook is licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & how to save it

### News

Introducing **Unsloth Studio** - a new open source, no-code web UI to train and run LLMs. [Blog](https://unsloth.ai/docs/new/studio) • [Notebook](https://colab.research.google.com/github/unslothai/unsloth/blob/main/studio/Unsloth_Studio_Colab.ipynb)

<table><tr>
<td align="center"><a href="https://unsloth.ai/docs/new/studio"><img src="https://unsloth.ai/docs/~gitbook/image?url=https%3A%2F%2F3215535692-files.gitbook.io%2F~%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252FxhOjnexMCB3dmuQFQ2Zq%252Fuploads%252FxV1PO5DbF3ksB51nE2Tw%252Fmore%2520cropped%2520ui%2520for%2520homepage.png%3Falt%3Dmedia%26token%3Df75942c9-3d8d-4b59-8ba2-1a4a38de1b86&width=376&dpr=3&quality=100&sign=a663c397&sv=2" width="200" height="120" alt="Unsloth Studio Training UI"></a><br><sub><b>Train models</b> — no code needed</sub></td>
<td align="center"><a href="https://unsloth.ai/docs/new/studio"><img src="https://unsloth.ai/docs/~gitbook/image?url=https%3A%2F%2F3215535692-files.gitbook.io%2F~%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252FxhOjnexMCB3dmuQFQ2Zq%252Fuploads%252FRCnTAZ6Uh88DIlU3g0Ij%252Fmainpage%2520unsloth.png%3Falt%3Dmedia%26token%3D837c96b6-bd09-4e81-bc76-fa50421e9bfb&width=376&dpr=3&quality=100&sign=c1a39da1&sv=2" width="200" height="120" alt="Unsloth Studio Chat UI"></a><br><sub><b>Run GGUF models</b> on Mac, Windows & Linux</sub></td>
</tr></table>

Train MoEs - DeepSeek, GLM, Qwen and gpt-oss 12x faster with 35% less VRAM. [Blog](https://unsloth.ai/docs/new/faster-moe)

Ultra Long-Context Reinforcement Learning is here with 7x more context windows! [Blog](https://unsloth.ai/docs/new/grpo-long-context)

New in Reinforcement Learning: [FP8 RL](https://unsloth.ai/docs/new/fp8-reinforcement-learning) • [Vision RL](https://unsloth.ai/docs/new/vision-reinforcement-learning-vlm-rl) • [Standby](https://unsloth.ai/docs/basics/memory-efficient-rl) • [gpt-oss RL](https://unsloth.ai/docs/new/gpt-oss-reinforcement-learning)

Visit our docs for all our [model uploads](https://unsloth.ai/docs/get-started/unsloth-model-catalog) and [notebooks](https://unsloth.ai/docs/get-started/unsloth-notebooks).

In [ ]:
!pip install modelscope
import os; os.environ['UNSLOTH_USE_MODELSCOPE'] = '1'
from unsloth import FastLanguageModel
model = FastLanguageModel.from_pretrained('unsloth/gpt-oss-20b')

### Installation

In [1]:
%%capture
import os

!pip install pip3-autoremove
!pip install torch torchvision torchaudio xformers --index-url https://download.pytorch.org/whl/cu128
!pip install unsloth
!pip install transformers==4.56.2
!pip install --no-deps trl==0.22.2

In [2]:
import torch
print(f"GPUs detected: {torch.cuda.device_count()}")
# Should return 2

GPUs detected: 2

In [8]:
torch.version.cuda

'12.8'

In [ ]:
!pip install modelscope
import os; os.environ['UNSLOTH_USE_MODELSCOPE'] = '1'
from unsloth import FastLanguageModel
model = FastLanguageModel.from_pretrained('unsloth/Qwen2.5-Coder-3B-Instruct-bnb-4bit')

Collecting modelscope
  Downloading modelscope-1.35.3-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 1.4 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from modelscope) (3.24.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from modelscope) (26.0)
Requirement already satisfied: requests>=2.25 in /usr/local/lib/python3.12/dist-packages (from modelscope) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from modelscope) (75.2.0)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.12/dist-packages (from modelscope) (4.67.3)
Requirement already satisfied: urllib3>=1.26 in /usr/local/lib/python3.12/dist-packages (from modelscope) (2.5.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25->modelscope) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25->modelscope) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25->modelscope) (2026.1.4)
Downloading modelscope-1.35.3-py3-none-any.whl (6.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 57.6 MB/s eta 0:00:0000:0100:01
Installing collected packages: modelscope
Successfully installed modelscope-1.35.3
==((====))==  Unsloth 2026.4.4: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 2. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

### Unsloth

In [3]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 32768 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

# 4bit pre quantized models we support for 4x faster downloading + no OOMs.
fourbit_models = [
    "unsloth/Qwen2.5-Coder-0.5B-Instruct-bnb-4bit",
    "unsloth/Qwen2.5-Coder-0.5B-Instruct",
    "unsloth/Qwen2.5-Coder-1.5B-Instruct-bnb-4bit",
    "unsloth/Qwen2.5-Coder-1.5B-Instruct",
    "unsloth/Qwen2.5-Coder-3B-Instruct",
    "unsloth/Qwen2.5-Coder-3B-Instruct-bnb-4bit",
    "unsloth/Qwen2.5-Coder-14B-Instruct",
    "unsloth/Qwen2.5-Coder-14B-Instruct-bnb-4bit",
    "unsloth/Qwen2.5-Coder-32B-Instruct-bnb-4bit",

] # More models at https://huggingface.co/unsloth

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Qwen2.5-Coder-3B-Instruct-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

2026-04-13 14:21:35.921921: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1776090096.154315      55 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1776090096.214884      55 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1776090096.764997      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1776090096.765030      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1776090096.765033      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1776090096.765035      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.4.4: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 2. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/2.05G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/266 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/632 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [4]:
model

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 2048, padding_idx=151665)
    (layers): ModuleList(
      (0-35): 36 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear4bit(in_features=2048, out_features=2048, bias=True)
          (k_proj): Linear4bit(in_features=2048, out_features=256, bias=True)
          (v_proj): Linear4bit(in_features=2048, out_features=256, bias=True)
          (o_proj): Linear4bit(in_features=2048, out_features=2048, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear4bit(in_features=2048, out_features=11008, bias=False)
          (up_proj): Linear4bit(in_features=2048, out_features=11008, bias=False)
          (down_proj): Linear4bit(in_features=11008, out_features=2048, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((2048,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((2048,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((2048,), eps=1e-06)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=2048, out_features=151936, bias=False)
)

We now add LoRA adapters so we only need to update 1 to 10% of all parameters!

In [5]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    import pandas as pd
df = pd.DataFrame(my_dataset)target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
)

Unsloth 2026.4.4 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

<a name="Data"></a>
### Dataset

We are using the [`open-r1/codeforces-cots`](https://huggingface.co/datasets/open-r1/codeforces-cots/viewer/solutions_decontaminated?views%5B%5D=solutions_decontaminated) by the Hugging Face Open R1 project. This is a dataset of problems for a competitive coding challenge.

The Open R1 team have found that models trained to reason on competitive coding tasks like this outperform other models on coding benchmarks.


![image](https://huggingface.co/open-r1/OlympicCoder-7B/resolve/main/lcb-evals.png)

In [6]:
from datasets import load_dataset

# Login using e.g. `huggingface-cli login` to access this dataset
ds = load_dataset("open-r1/codeforces-cots", "solutions_decontaminated")

README.md: 0.00B [00:00, ?B/s]

solutions_decontaminated/train-00000-of-(…):   0%|          | 0.00/171M [00:00<?, ?B/s]

solutions_decontaminated/train-00001-of-(…):   0%|          | 0.00/140M [00:00<?, ?B/s]

KeyboardInterrupt:

In [1]:
from datasets import load_dataset, Dataset
from itertools import islice

# 1. Start streaming (fast, no full download)
ds = load_dataset(
    "open-r1/codeforces-cots", 
    name="solutions_decontaminated", 
    split="train", 
    streaming=True
)

# 2. Filter for 'A' type and grab exactly 2000
a_stream = ds.filter(lambda x: x['id'].endswith('A'))
data_list = list(islice(a_stream, 2000))

# 3. CONVERT TO DATASET (This is what you want)
my_dataset = Dataset.from_list(data_list)

print(type(my_dataset))
# Output: <class 'datasets.arrow_dataset.Dataset'>
print(my_dataset)

/home/d0lph1n/miniconda3/envs/py3.12/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

<class 'datasets.arrow_dataset.Dataset'>
Dataset({
    features: ['id', 'aliases', 'contest_id', 'contest_name', 'contest_type', 'contest_start', 'contest_start_year', 'index', 'time_limit', 'memory_limit', 'title', 'description', 'input_format', 'output_format', 'examples', 'note', 'editorial', 'problem', 'generation', 'finish_reason', 'api_metadata', 'interaction_format', 'messages', 'problem_type', 'public_tests', 'private_tests', 'generated_tests', 'public_tests_ms', 'failed_solutions', 'accepted_solutions'],
    num_rows: 2000
})

In [2]:
# Split the dataset (80% train, 20% test)
split_dataset = my_dataset.train_test_split(test_size=0.2, seed=42)

# This creates a 'DatasetDict' containing both sets
print(split_dataset)

# To access them individually:
train_ds = split_dataset['train']
test_ds = split_dataset['test']

print(f"Train size: {len(train_ds)}")
print(f"Test size: {len(test_ds)}")

DatasetDict({
    train: Dataset({
        features: ['id', 'aliases', 'contest_id', 'contest_name', 'contest_type', 'contest_start', 'contest_start_year', 'index', 'time_limit', 'memory_limit', 'title', 'description', 'input_format', 'output_format', 'examples', 'note', 'editorial', 'problem', 'generation', 'finish_reason', 'api_metadata', 'interaction_format', 'messages', 'problem_type', 'public_tests', 'private_tests', 'generated_tests', 'public_tests_ms', 'failed_solutions', 'accepted_solutions'],
        num_rows: 1600
    })
    test: Dataset({
        features: ['id', 'aliases', 'contest_id', 'contest_name', 'contest_type', 'contest_start', 'contest_start_year', 'index', 'time_limit', 'memory_limit', 'title', 'description', 'input_format', 'output_format', 'examples', 'note', 'editorial', 'problem', 'generation', 'finish_reason', 'api_metadata', 'interaction_format', 'messages', 'problem_type', 'public_tests', 'private_tests', 'generated_tests', 'public_tests_ms', 'failed_solutions', 'accepted_solutions'],
        num_rows: 400
    })
})
Train size: 1600
Test size: 400

In [25]:
import pandas as pd
df = pd.DataFrame(my_dataset)m

In [29]:
df

,id,aliases,contest_id,contest_name,contest_type,contest_start,contest_start_year,index,time_limit,memory_limit,...,api_metadata,interaction_format,messages,problem_type,public_tests,private_tests,generated_tests,public_tests_ms,failed_solutions,accepted_solutions
0,1991/A,None,1991,Pinely Round 4 (Div. 1 + Div. 2),CF,1722177300,2024,A,1.0,256.0,...,"{'completion_tokens': 2504, 'prompt_tokens': 8...",None,[{'content': 'You will be given a competitive ...,diff,None,None,None,None,None,"[{'code': '#include ""bits/stdc++.h"" #define i..."
1,1991/A,None,1991,Pinely Round 4 (Div. 1 + Div. 2),CF,1722177300,2024,A,1.0,256.0,...,"{'completion_tokens': 3477, 'prompt_tokens': 8...",None,[{'content': 'You will be given a competitive ...,diff,None,None,None,None,None,"[{'code': '#include ""bits/stdc++.h"" #define i..."
2,1991/A,None,1991,Pinely Round 4 (Div. 1 + Div. 2),CF,1722177300,2024,A,1.0,256.0,...,"{'completion_tokens': 2260, 'prompt_tokens': 8...",None,[{'content': 'You will be given a competitive ...,diff,None,None,None,None,None,"[{'code': '#include ""bits/stdc++.h"" #define i..."
3,1991/A,None,1991,Pinely Round 4 (Div. 1 + Div. 2),CF,1722177300,2024,A,1.0,256.0,...,"{'completion_tokens': 1978, 'prompt_tokens': 8...",None,[{'content': 'You will be given a competitive ...,diff,None,None,None,None,None,"[{'code': '#include ""bits/stdc++.h"" #define i..."
4,1991/A,None,1991,Pinely Round 4 (Div. 1 + Div. 2),CF,1722177300,2024,A,1.0,256.0,...,"{'completion_tokens': 3863, 'prompt_tokens': 8...",None,[{'content': 'You will be given a competitive ...,diff,None,None,None,None,None,"[{'code': '#include ""bits/stdc++.h"" #define i..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1760/A,None,1760,Codeforces Round 835 (Div. 4),ICPC,1669041300,2022,A,1.0,256.0,...,"{'completion_tokens': 792, 'prompt_tokens': 37...",None,[{'content': 'You will be given a competitive ...,diff,None,None,None,None,None,None
1996,1760/A,None,1760,Codeforces Round 835 (Div. 4),ICPC,1669041300,2022,A,1.0,256.0,...,"{'completion_tokens': 1145, 'prompt_tokens': 3...",None,[{'content': 'You will be given a competitive ...,diff,None,None,None,None,None,None
1997,1760/A,None,1760,Codeforces Round 835 (Div. 4),ICPC,1669041300,2022,A,1.0,256.0,...,"{'completion_tokens': 1473, 'prompt_tokens': 3...",None,[{'content': 'You will be given a competitive ...,diff,None,None,None,None,None,None
1998,1760/A,None,1760,Codeforces Round 835 (Div. 4),ICPC,1669041300,2022,A,1.0,256.0,...,"{'completion_tokens': 704, 'prompt_tokens': 37...",None,[{'content': 'You will be given a competitive ...,diff,None,None,None,None,None,None
1999,1760/A,None,1760,Codeforces Round 835 (Div. 4),ICPC,1669041300,2022,A,1.0,256.0,...,"{'completion_tokens': 1413, 'prompt_tokens': 3...",None,[{'content': 'You will be given a competitive ...,diff,None,None,None,None,None,None

In [35]:
df.columns

Index(['id', 'aliases', 'contest_id', 'contest_name', 'contest_type',
       'contest_start', 'contest_start_year', 'index', 'time_limit',
       'memory_limit', 'title', 'description', 'input_format', 'output_format',
       'examples', 'note', 'editorial', 'problem', 'generation',
       'finish_reason', 'api_metadata', 'interaction_format', 'messages',
       'problem_type', 'public_tests', 'private_tests', 'generated_tests',
       'public_tests_ms', 'failed_solutions', 'accepted_solutions'],
      dtype='object')

In [48]:
df[df['id']=='1991/A']['messages'][0]

[{'content': 'You will be given a competitive programming problem. Please reason step by step about the solution, then provide a complete implementation in C++17.\n\nYour solution must read input from standard input (cin), write output to standard output (cout).\nDo not include any debug prints or additional output.\n\nPut your final solution within a single code block:\n```cpp\n<your code here>\n```\n\n# Problem\n\nYou are given an array $$$a$$$ of $$$n$$$ integers, where $$$n$$$ is odd.\n\nIn one operation, you will remove two adjacent elements from the array $$$a$$$, and then concatenate the remaining parts of the array. For example, given the array $$$[4,7,4,2,9]$$$, we can obtain the arrays $$$[4,2,9]$$$ and $$$[4,7,9]$$$ by the operations $$$[\\underline{4,7}, 4,2,9] \\to [4,2,9]$$$ and $$$[4,7,\\underline{4,2},9] \\to [4,7,9]$$$ respectively. However, we cannot obtain the array $$$[7,2,9]$$$ as it requires deleting non-adjacent elements $$$[\\underline{4},7,\\underline{4},2,9]$$$.\n\nYou will repeatedly perform this operation until exactly one element remains in $$$a$$$.\n\nFind the maximum possible value of the remaining element in $$$a$$$.\n\nExecution time limit: 1.0 seconds\nMemory limit: 256.0 MB\n\n## Input Format\nEach test contains multiple test cases. The first line contains a single integer $$$t$$$ ($$$1 \\le t \\le 1000$$$)\xa0— the number of test cases. The description of test cases follows.\n\nThe first line of each test case contains a single integer $$$n$$$ ($$$1 \\le n \\le 99$$$; $$$n$$$ is odd)\xa0— the length of the array $$$a$$$.\n\nThe second line of each test case contains $$$n$$$ integers $$$a_1, a_2, \\ldots, a_n$$$ ($$$1 \\le a_i \\le 100$$$)\xa0— the elements of the array $$$a$$$.\n\nNote that there is no bound on the sum of $$$n$$$ over all test cases.\n\n## Output Format\nFor each test case, output a single integer\xa0— the maximum possible value of the remaining element in $$$a$$$.\n\n## Examples\n```input\n4\n1\n6\n3\n1 3 2\n5\n4 7 4 2 9\n7\n3 1 4 1 5 9 2\n```\n```output\n6\n2\n9\n5\n```\n\n## Note\nIn the first test case, the array $$$a$$$ is $$$[6]$$$. Since there is only one element, no operations are needed. The maximum possible value of the remaining element is $$$6$$$.\n\nIn the second test case, the array $$$a$$$ is $$$[1, 3, 2]$$$. We can remove the first two elements $$$[\\underline{1, 3}, 2] \\to [2]$$$, or remove the last two elements $$$[1, \\underline{3, 2}] \\to [1]$$$. Therefore, the maximum possible value of the remaining element is $$$2$$$.\n\nIn the third test case, the array $$$a$$$ is $$$[4, 7, 4, 2, 9]$$$. One way to maximize the remaining element is $$$[4, \\underline{7, 4}, 2, 9] \\to [\\underline{4, 2}, 9] \\to [9]$$$. Therefore, the maximum possible value of the remaining element is $$$9$$$.\n\nIn the fourth test case, the array $$$a$$$ is $$$[3, 1, 4, 1, 5, 9, 2]$$$. It can be shown that the maximum possible value of the remaining element is $$$5$$$.\n',
  'role': 'user'},
 {'content': "<think>\nOkay, let's try to figure out how to solve this problem. The problem is that we have an array of odd length, and we can repeatedly remove pairs of adjacent elements until there's one left. We need to find the maximum possible remaining element after all possible operations.\n\nHmm. Let's think about the process. Each operation removes two adjacent elements. Since the array length is odd, after each operation the length decreases by 1 (because 2 are removed, so the new length is n-2 + ... wait, no. Wait, when you remove two adjacent elements, the array's length reduces by 2 each time. Wait, the original array length is n, which is odd. Then after each operation, the length becomes n-2, which is odd minus 2, which is even? Wait no, wait. Wait, n is odd. For example, if n is 3, after removing two elements, the length is 1. Which is odd. Wait, so each operation reduces the length by 2. So the parity of the length remains odd. Because subtracting 2 from an odd number gives another odd number. Wait, no. Wait 3-2=1 (odd), 1-2=-1, which is not possible. So the process stops when the length is 1. So for the starting n which is odd, after each operation the length is n-2, which is again odd, until it reaches 1.\n\nSo the process will take (n-1)/2 steps. Because each step removes two elements, so (n-1)/2 steps to get from n to 1.\n\nBut how to model which elements can be kept. The key is to find a selection of elements where each step removes two adjacent elements, and the remaining elements form a possible path of removal steps leading to that element being the last one.\n\nWait, perhaps there's a pattern here. Let's look at the examples.\n\nIn the second test case: 3 elements. The options are to remove the first two, leaving the third, or remove the last two, leaving the first. So the maximum is the maximum of the first or third element. But in the example given, the array is [1,3,2]. The options are 2 or 1, so maximum is 2. But the third element is 2. Wait, so that's the case. So for n=3, the maximum is the maximum of the elements at positions 0, 2 (assuming 0-based indexing). Because after removing the first two, you get the third. Or removing the last two, you get the first.\n\nWait, that's interesting. So for n=3, the last remaining element can be either the first or the third. So the maximum is the maximum of those two.\n\nWhat about n=5. Let's take the third example: [4,7,4,2,9]. The solution was 9, which is the fifth element. How did that happen? Let's see the steps. They first removed 7 and 4 (the second and third elements), leading to [4,2,9]. Then in that array, they removed 4 and 2, leading to 9. So the final element is the fifth element of the original array.\n\nAlternatively, for a 5-element array, maybe the possible elements that can remain are those at positions 0, 2, 4. Because when you start with 5 elements, after each removal step, you have 3, then 1. So maybe the positions that are even indices in the original array can be the ones that are kept.\n\nWait, perhaps the answer is that the maximum element among the elements at the even indices (0, 2, 4, etc.) is the answer. Because when you have an array of odd length, each time you remove two adjacent elements, the remaining elements' positions depend on which pair was removed.\n\nWait, for example, in the 5-element array. Let's say the array is a0, a1, a2, a3, a4. If you remove a1 and a2, then the remaining array is a0, a3, a4. Then, in the next step, you can remove a0 and a3 (leaving a4), or a3 and a4 (leaving a0). So in this path, the final element is a4 or a0.\n\nAlternatively, if you first remove a3 and a4, then the remaining array is a0, a1, a2. Then next step removes a0 and a1, leaving a2. So the final element is a2.\n\nAnother possibility: first remove a0 and a1, leaving a2, a3, a4. Then next step removes a3 and a4, leaving a2. So the final element is a2.\n\nSo for a 5-element array, the possible final elements are a0, a2, a4. So the maximum is the maximum of these three.\n\nIf that's the case, then for the third example in the input, the elements at even indices (0,2,4) are 4,4,9. The maximum is 9, which matches the sample output.\n\nSimilarly, in the fourth example, the input array is [3,1,4,1,5,9,2] (n=7). The even indices are 0,2,4,6. The elements are 3,4,5,2. The maximum is 5, which matches the sample output.\n\nAnother sample is the second test case (n=3): even indices 0 and 2. Elements are 1 and 2. Max is 2.\n\nSo this seems to fit all the examples.\n\nSo the solution is: for the array of odd length n, the maximum possible remaining element is the maximum among all elements at even indices (0-based). Because those are the positions that could end up as the last element after removing pairs in a certain way.\n\nWait, why is that the case? Let's think recursively. For an array of length 1, the only element is the answer. For an array of length 3, you can remove the first two elements (leaving the third) or the last two (leaving the first). So the answer is max of first and third. For length 5, the possible elements that can be left are the first, third, fifth elements, because each step of removing pairs can leave the even positions.\n\nBut how to see this pattern holds for any odd n?\n\nHmm. Let's think for n=5. The possible elements that can be left after all operations are the elements at positions 0, 2, 4.\n\nSimilarly, for n=7, the possible elements are 0, 2,4,6.\n\nSo the pattern is that the positions that can be the last element are those with even indices (0, 2, 4, ..., n-1). Because when you remove pairs, the even indices can be preserved.\n\nWait, but how exactly? For example, in the 5-element array, how can a2 be preserved?\n\nIn the example where you first remove a3 and a4, then the array is a0, a1, a2. Then you can remove a0 and a1, leaving a2. So in that case, a2 is the last element.\n\nSo the key insight is that when you remove pairs in such a way that certain elements are skipped, you can end up with any even index element as the last remaining.\n\nTherefore, the answer is simply the maximum value among the elements at even positions (0, 2, 4, ...) in the original array.\n\nSo the solution is to iterate over all elements in even indices and find the maximum.\n\nThat's a very simple solution. So the code would be, for each test case, read the array, iterate through the elements at even indices (0, 2, 4, etc.), and take the maximum.\n\nLet me check the samples again.\n\nFirst sample: n=1. The only element is at index 0, which is even. So answer is 6. Correct.\n\nSecond sample: n=3. Indices 0 and 2. Max of 1 and 2 is 2. Correct.\n\nThird sample: n=5. Indices 0, 2,4. Values 4,4,9. Max 9. Correct.\n\nFourth sample: n=7. Indices 0,2,4,6. Values 3,4,5,2. Max 5. Correct.\n\nYes, all the samples are covered by this approach.\n\nSo the problem reduces to selecting the maximum element from the even indices of the array.\n\nTherefore, the code is straightforward. Read t test cases. For each, read n, then the array. Then loop through the array, check the elements at even indices (i=0,2,4,...,n-1), and take the maximum.\n\nThat's it. So this solution should work.\n\nSo the code would be:\n\nFor each test case:\n\nRead n.\n\nRead the array a.\n\nInitialize max_val to a[0].\n\nThen for i from 2 to n-1, stepping by 2:\n\nif a[i] > max_val, update max_val.\n\nThen output max_val.\n\nYes.\n\nNow let's write the code.\n\nIn C++, the steps would be:\n\nRead t.\n\nLoop t times:\n\nRead n.\n\nRead n integers into a vector.\n\nInitialize the maximum as a[0].\n\nLoop i from 2 to n-1, step 2 (i += 2):\n\nCompare and update the maximum.\n\nPrint the maximum.\n\nWait, for n=1, the loop runs from 2 to 0, which is not executed. So the maximum remains a[0], which is correct.\n\nYes.\n\nSo the code would look like:\n\n#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    int t;\n    cin >> t;\n    while (t--) {\n        int n;\n        cin >> n;\n        vector<int> a(n);\n        for (int i=0; i<n; i++) {\n            cin >> a[i];\n        }\n        int max_val = a[0];\n        for (int i=2; i <n; i +=2) {\n            if (a[i] > max_val) {\n                max_val = a[i];\n            }\n        }\n        cout << max_val << endl;\n    }\n    return 0;\n}\n\nTesting this code against the samples.\n\nSample 1:\n\nInput:\n\n4\n\n1\n\n6\n\nOutput 6.\n\nSample 2:\n\n3\n\n1 3 2. The even indices are 0 and 2. Values 1 and 2. Max is 2.\n\nSample3:\n\n5\n\n4 7 4 2 9. Even indices 0,2,4. Values 4,4,9. Max is9.\n\nSample4:\n\n7\n\n3 1 4 1 5 9 2. Even indices 0 (3), 2 (4), 4 (5), 6 (2). Max is 5.\n\nAll correct.\n\nSo this code should pass all test cases.\n\nThus, the solution is to take the maximum among elements at even indices.\n</think>\n\n```cpp\n#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    int t;\n    cin >> t;\n    while (t--) {\n        int n;\n        cin >> n;\n        vector<int> a(n);\n        for (int i = 0; i < n; ++i) {\n            cin >> a[i];\n        }\n        int max_val = a[0];\n        for (int i = 2; i < n; i += 2) {\n            if (a[i] > max_val) {\n                max_val = a[i];\n            }\n        }\n        cout << max_val << '\\n';\n    }\n    return 0;\n}\n```",
  'role': 'assistant'}]

In [52]:
df[df['id']=='1991/A']['messages'][1]

[{'content': 'You will be given a competitive programming problem. Please reason step by step about the solution, then provide a complete implementation in C++17.\n\nYour solution must read input from standard input (cin), write output to standard output (cout).\nDo not include any debug prints or additional output.\n\nPut your final solution within a single code block:\n```cpp\n<your code here>\n```\n\n# Problem\n\nYou are given an array $$$a$$$ of $$$n$$$ integers, where $$$n$$$ is odd.\n\nIn one operation, you will remove two adjacent elements from the array $$$a$$$, and then concatenate the remaining parts of the array. For example, given the array $$$[4,7,4,2,9]$$$, we can obtain the arrays $$$[4,2,9]$$$ and $$$[4,7,9]$$$ by the operations $$$[\\underline{4,7}, 4,2,9] \\to [4,2,9]$$$ and $$$[4,7,\\underline{4,2},9] \\to [4,7,9]$$$ respectively. However, we cannot obtain the array $$$[7,2,9]$$$ as it requires deleting non-adjacent elements $$$[\\underline{4},7,\\underline{4},2,9]$$$.\n\nYou will repeatedly perform this operation until exactly one element remains in $$$a$$$.\n\nFind the maximum possible value of the remaining element in $$$a$$$.\n\nExecution time limit: 1.0 seconds\nMemory limit: 256.0 MB\n\n## Input Format\nEach test contains multiple test cases. The first line contains a single integer $$$t$$$ ($$$1 \\le t \\le 1000$$$)\xa0— the number of test cases. The description of test cases follows.\n\nThe first line of each test case contains a single integer $$$n$$$ ($$$1 \\le n \\le 99$$$; $$$n$$$ is odd)\xa0— the length of the array $$$a$$$.\n\nThe second line of each test case contains $$$n$$$ integers $$$a_1, a_2, \\ldots, a_n$$$ ($$$1 \\le a_i \\le 100$$$)\xa0— the elements of the array $$$a$$$.\n\nNote that there is no bound on the sum of $$$n$$$ over all test cases.\n\n## Output Format\nFor each test case, output a single integer\xa0— the maximum possible value of the remaining element in $$$a$$$.\n\n## Examples\n```input\n4\n1\n6\n3\n1 3 2\n5\n4 7 4 2 9\n7\n3 1 4 1 5 9 2\n```\n```output\n6\n2\n9\n5\n```\n\n## Note\nIn the first test case, the array $$$a$$$ is $$$[6]$$$. Since there is only one element, no operations are needed. The maximum possible value of the remaining element is $$$6$$$.\n\nIn the second test case, the array $$$a$$$ is $$$[1, 3, 2]$$$. We can remove the first two elements $$$[\\underline{1, 3}, 2] \\to [2]$$$, or remove the last two elements $$$[1, \\underline{3, 2}] \\to [1]$$$. Therefore, the maximum possible value of the remaining element is $$$2$$$.\n\nIn the third test case, the array $$$a$$$ is $$$[4, 7, 4, 2, 9]$$$. One way to maximize the remaining element is $$$[4, \\underline{7, 4}, 2, 9] \\to [\\underline{4, 2}, 9] \\to [9]$$$. Therefore, the maximum possible value of the remaining element is $$$9$$$.\n\nIn the fourth test case, the array $$$a$$$ is $$$[3, 1, 4, 1, 5, 9, 2]$$$. It can be shown that the maximum possible value of the remaining element is $$$5$$$.\n',
  'role': 'user'},
 {'content': "<think>\nOkay, let's see. I need to find the maximum possible remaining element after repeatedly removing pairs of adjacent elements until one is left. Hmm. The key here is to figure out which elements can be the last remaining one, and then pick the maximum among them.\n\nWait, how does the process work? Since each operation removes two adjacent elements, the positions of the elements left depend on which pairs are removed. For example, if the array is [a, b, c], you can remove a and b, leaving c. Or remove b and c, leaving a. So in that case, the possible remaining elements are a or c. So for odd-length arrays, maybe the elements that can be left are those at certain positions based on the steps taken.\n\nWait, the initial array has length n (odd). Each operation reduces the length by 2. So after (n-1)/2 operations, we'll have 1 element left. So for example, n=5: after 2 operations (5-2*2=1). \n\nBut how does the selection of which pairs to remove affect which elements remain? Let's think recursively. For a given array, the remaining element must have been present in the array such that all elements to the left and right are paired in a way that allows this element to be the last. \n\nHmm. Let's think about the possible positions. For example, in the sample input where n=3, the possible remaining elements are the first or the third. Wait no, in that sample, the array is [1,3,2]. If you remove 1 and 3, you get 2. If you remove 3 and 2, you get 1. So the possible remaining elements are 1 or 2. The maximum is 2. So the middle element (3) cannot be chosen. Wait, why? Because when you have 3 elements, you can only remove the first two or the last two. So the middle element can't be the last one. \n\nWait, so maybe the elements that can be left are those at positions with even or odd indices, but considering how many steps are taken. Wait, perhaps the elements that can remain are those at positions that have a certain parity. For example, in the case of n=3, the possible positions are 0 and 2 (if 0-based). So their indices are even (0 and 2). But in the case of n=5, perhaps the possible positions are 0, 2, 4? Let's see. Suppose we have a 5-element array. Each time we remove two adjacent elements. Let's say the first step is to remove elements 1 and 2 (0-based indices), leaving elements 0, 3,4. Then in the next step, we can remove 0 and 3 (they are adjacent now?), wait the array is [0,3,4]. So indices 0 and 1. Removing them leaves 4. Alternatively, first removing 3 and4 (elements 3 and4), which leaves [0,1,2], then remove 1 and2, leaving 0. Hmm, so the remaining element can be 0, 4, or maybe other possibilities. Wait, but maybe the positions that can be left are those that are at even indices in the original array when considering the steps of elimination. \n\nAlternatively, think of the process as building a selection of elements that are kept. For the last element to be at position i, the elements on the left and right must be paired in such a way that i is left. For example, in a 5-element array, the possible positions could be 0, 2, 4. Wait, but how? Let's take the example from the third test case: [4,7,4,2,9]. The solution is to leave 9. The steps were: remove 7 and4 (indices 1 and2), then 4 and2 (indices 0 and1 of the new array [4,2,9]?), leading to 9. Wait, maybe the way to model this is that the positions that can be the last remaining one are those that are at even distances from the start and end. \n\nAnother approach: the remaining element must be such that there are an even number of elements on each side. Because each step removes two elements, so the number of elements on each side must be even. Let's see. For example, in the 3-element case. If we want to leave the first element (position 0), then the two elements to the right (positions 1 and 2) must be removed. So they form one pair, which is allowed. Similarly for the third element. For the middle element (position 1), the elements to the left (0) and right (2) are each one element, which is odd. So we can't pair them. Hence the middle can't be left. So for n=3, possible positions are 0 and 2.\n\nFor n=5: to leave position 0. Then the elements 1-4 (positions 1-4) must be removed in pairs. That's four elements, which is even, so possible. For position 2: left (positions 0-1) must be two elements (even), and right (positions 3-4) must be two elements (even). So possible. For position 4: similar to position 0. So possible positions are 0,2,4. So the maximum among those is selected.\n\nWait, but how does that hold for larger n? Let's see for n=5. Let's say we have a 5-element array. If we want to leave position 2, then the left has 2 elements (positions 0-1) and the right has 2 elements (positions 3-4). So those can be removed in pairs, leaving position 2.\n\nSimilarly, for n=7, the possible positions would be 0, 2,4,6. Because for each of those positions, the elements to the left and right are even in number. Wait, but let's see. For example, if we want to leave position 3 in a 7-element array, the left has 3 elements (0-2) which is odd. So can't pair them all. So position 3 can't be left. So for n=7, possible positions are 0,2,4,6. So the maximum among those is the answer.\n\nSo the general pattern seems to be that for an array of length n (odd), the possible positions are those that are even in 0-based indices. Wait, wait. Wait for n=3, positions 0 and 2 are even. For n=5, positions 0,2,4. For n=7, 0,2,4,6. So the possible positions are the even indices. Because the indices start from 0. Wait, 0,2,4, etc., up to n-1, which is even (since n is odd). So for example, in n=5, n-1 is 4, which is even. So the possible positions are all even indices. \n\nSo the solution is to take the maximum element among all elements at even indices (0,2,4,...) in the original array. Because regardless of the operations, those are the only possible elements that can remain. \n\nWait, but why? Because each operation removes two adjacent elements, but the way to preserve a certain element is to have even numbers of elements on both sides. Because each step removes two elements, so each side must be even in count so that they can be completely removed. \n\nSo for any element at position i in the original array, the number of elements to the left (i) must be even, and the number to the right (n-1 -i) must also be even. Because those elements must be removed in pairs. \n\nSo for left count: i elements. For this to be even, i must be even. Similarly, the right count is (n-1 -i). For this to be even, (n-1 -i) must be even. Since n is odd, (n-1) is even. So (even - i) must be even. So i must be even. \n\nSo both left and right must be even. So i must be even. Because i is even, then (even - i) is even (since even minus even is even). \n\nWait, let's check. For example, n=3 (n-1=2 even). So for i=0: left is 0 elements (even), right is 2 elements (even). So possible. For i=2: left is 2 (even), right 0 (even). So possible. For i=1 (middle): left is 1 (odd), can't be removed. So impossible.\n\nSo the conclusion is that the element must be at an even index in the original array. Then, the maximum among these elements is the answer. \n\nWait, that's a really simple solution. So the code would be, for each test case, iterate over the elements at even indices (0, 2, 4, ...) and take the maximum. \n\nLet's check the examples:\n\nFirst example: n=1. Only index 0. Max is 6. Correct.\n\nSecond example: [1,3,2]. Indices 0,2. Elements 1 and 2. Max is 2. Correct.\n\nThird example: [4,7,4,2,9]. Even indices 0,2,4. Elements 4,4,9. Max is 9. Correct.\n\nFourth example: [3,1,4,1,5,9,2]. Even indices 0,2,4,6. Elements 3,4,5,2. Max is 5. Correct.\n\nSo this approach works for all test cases. So the solution is to select the maximum element in even positions (0-based).\n\nSo the code is straightforward: for each array, check all elements at even indices and take the maximum. Then output that.\n\nSo the steps are:\n\nRead t test cases.\n\nFor each test case:\n\nRead n, then the array a.\n\nCompute the maximum of a[i] where i is even (0,2,4,...).\n\nOutput that maximum.\n\nYes, that's the correct approach. So the code is simple. For example, in C++:\n\nLoop through the array, step by 2 (i += 2), and track the maximum.\n\nSo the code would be:\n\nRead t.\n\nFor each t:\n\nread n.\n\nread the array.\n\ninitialize max_val to a[0], then for i from 2 to n-1 step 2:\n\nif a[i] > max_val, update max_val.\n\nprint max_val.\n\nYes. So this code will handle all test cases correctly.\n\nNow, let's code this.\n\nBut wait, for n=1, the array has one element. So the code will process that correctly.\n\nSo the code is:\n\n#include <iostream>\n#include <vector>\n#include <algorithm>\n\nusing namespace std;\n\nint main() {\n    int t;\n    cin >> t;\n    while (t--) {\n        int n;\n        cin >> n;\n        vector<int> a(n);\n        for (int i = 0; i < n; ++i) {\n            cin >> a[i];\n        }\n        int max_val = a[0];\n        for (int i = 2; i < n; i += 2) {\n            if (a[i] > max_val) {\n                max_val = a[i];\n            }\n        }\n        cout << max_val << '\\n';\n    }\n    return 0;\n}\n\nWait, but why is that correct? Because for n being odd, the indices 0,2,4...n-1 (since n is odd, n-1 is even). So the loop from 0 to n-1, stepping by 2. But in the code above, the initial max_val is a[0], then starting from i=2, step 2. But perhaps a better way is to loop through all even indices, i.e., for i in 0,2,4,...,n-1.\n\nSo maybe the code can be written as:\n\nfor (int i = 0; i < n; i += 2) { ... }\n\nYes. That way, all even indices are considered. So for example, when n is 5, i will be 0,2,4. Which is correct.\n\nSo the code should be:\n\nint max_val = a[0];\nfor (int i = 0; i < n; i += 2) {\n    if (a[i] > max_val) {\n        max_val = a[i];\n    }\n}\n\nBut wait, initially setting max_val to a[0] and then starting the loop from i=0 is redundant. So the code can be written as:\n\nint max_val = 0;\nfor (int i = 0; i < n; i += 2) {\n    if (a[i] > max_val || i == 0) {\n        max_val = a[i];\n    }\n}\n\nWait no. Alternatively, initialize max_val to a[0], then loop from i=2. But the code can be simplified by looping from i=0 and comparing.\n\nWait, the correct code would be:\n\nmax_val is the maximum of a[0], a[2], a[4], ..., a[n-1].\n\nSo in code:\n\nint max_val = a[0];\nfor (int i = 2; i < n; i += 2) {\n    max_val = max(max_val, a[i]);\n}\n\nBut that's equivalent to checking all even indices starting from 0. Because for i=0, we start with a[0], then check a[2], a[4], etc. So the code is correct.\n\nAlternatively, the loop can start at i=0. Because:\n\nint max_val = a[0];\nfor (int i = 0; i < n; i += 2) {\n    if (a[i] > max_val) {\n        max_val = a[i];\n    }\n}\n\nWait, but in this case, the first iteration is i=0, which compares a[0] with max_val (which is a[0]), so no change. Then i=2, etc. So it's the same. But if we initialize max_val to a[0], and then loop from i=2, then for i=2, we check a[2], etc. So the code in the first example would work.\n\nBut perhaps the code can be written in a more straightforward way: iterate through all even indices and keep track of the maximum.\n\nIn code:\n\nint max_val = a[0];\nfor (int i = 2; i < n; i += 2) {\n    if (a[i] > max_val) {\n        max_val = a[i];\n    }\n}\n\nYes. Because the even indices are 0,2,4,...,n-1. So the first element is a[0], then check a[2], etc.\n\nSo this code would work.\n\nTesting the examples:\n\nFourth example input: 7 elements. The even indices are 0,2,4,6. The elements are 3,4,5,2. The maximum is 5. Correct.\n\nThird example: elements at even indices are 4,4,9. Max is 9.\n\nSecond example: even indices 0,2. Elements 1, 2. Max is 2.\n\nYes.\n\nSo this code will work. So the solution is to take the maximum of the elements at even indices in the original array.\n\nThat's the correct approach.\n</think>\n\n```cpp\n#include <iostream>\n#include <vector>\n\nusing namespace std;\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(nullptr);\n    \n    int t;\n    cin >> t;\n    while (t--) {\n        int n;\n        cin >> n;\n        vector<int> a(n);\n        for (int& x : a) {\n            cin >> x;\n        }\n        int max_val = a[0];\n        for (int i = 2; i < n; i += 2) {\n            if (a[i] > max_val) {\n                max_val = a[i];\n            }\n        }\n        cout << max_val << '\\n';\n    }\n    return 0;\n}\n```",
  'role': 'assistant'}]

In [13]:
tokenizer.apply_chat_template(
    train_ds["messages"][0], tokenize = False
)

'<|im_start|>system\nYou are Qwen, created by Alibaba Cloud. You are a helpful assistant.<|im_end|>\n<|im_start|>user\nYou will be given a competitive programming problem. Please reason step by step about the solution, then provide a complete implementation in C++17.\n\nYour solution must read input from standard input (cin), write output to standard output (cout).\nDo not include any debug prints or additional output.\n\nPut your final solution within a single code block:\n```cpp\n<your code here>\n```\n\n# Problem\n\nYou are given an integer $$$n$$$.\n\nFind any pair of integers $$$(x,y)$$$ ($$$1\\leq x,y\\leq n$$$) such that $$$x^y\\cdot y+y^x\\cdot x = n$$$.\n\nExecution time limit: 1.0 seconds\nMemory limit: 256.0 MB\n\n## Input Format\nThe first line contains a single integer $$$t$$$ ($$$1\\leq t\\leq 10^4$$$) — the number of test cases.\n\nEach test case contains one line with a single integer $$$n$$$ ($$$1\\leq n\\leq 10^9$$$).\n\n## Output Format\nFor each test case, if possible, print two integers $$$x$$$ and $$$y$$$ ($$$1\\leq x,y\\leq n$$$). If there are multiple answers, print any.\n\nOtherwise, print $$$-1$$$.\n\n## Examples\n```input\n5\n3\n7\n42\n31250\n20732790\n```\n```output\n-1\n-1\n2 3\n5 5\n3 13\n```\n\n## Note\nIn the third test case, $$$2^3 \\cdot 3+3^2 \\cdot 2 = 42$$$, so $$$(2,3),(3,2)$$$ will be considered as legal solutions.\n\nIn the fourth test case, $$$5^5 \\cdot 5+5^5 \\cdot 5 = 31250$$$, so $$$(5,5)$$$ is a legal solution.\n<|im_end|>\n<|im_start|>assistant\n<think>\nOkay, let\'s see. I need to find x and y such that x^y * y + y^x * x equals n. And the constraints are that x and y are between 1 and n. Hmm. For each test case, I have to check possible pairs (x, y) and see if they satisfy the equation. But wait, n can be up to 1e9 and t is up to 1e4. So a brute-force approach checking all possible pairs for each n isn\'t feasible. That\'s going to be too slow. So I need a smarter way to find possible x and y.\n\nLet me think about possible small values. Let\'s see the examples. For n=42, the solution is 2 and 3. Let\'s compute: 2^3 is 8, multiplied by 3 gives 24. 3^2 is 9, multiplied by 2 gives 18. 24 +18=42. So that works. Another example is when x and y are the same. Like in the fourth test case, 5^5 *5 + 5^5*5 = 2*5^5*5. 5^5 is 3125, multiplied by 5 is 15625. Times 2 is 31250. So that\'s how it works.\n\nSo maybe checking small x and y first would help. Because for larger x and y, the value could get too big, but since n is up to 1e9, maybe the possible solutions are limited to small x and y.\n\nLet me think about possible x and y values. Let\'s consider possible cases.\n\nCase 1: x=1. Then the equation becomes 1^y * y + y^1 *1 = y + y*1 = 2y. So 2y =n. So y must be n/2, and n must be even. So if n is even, then x=1 and y=n/2 (if y <=n). But wait, since y has to be <=n. So for example, if n is even and n/2 <=n (which is always true unless n=0, but n is at least 1 here), then (1, n/2) is a solution. So for any even n >=2, maybe that\'s possible. Wait, but in the sample input, n=3 is the first case. It\'s 3, which is odd. So output is -1. The second test case is 7, which is odd, so output is -1. But the fourth test case is 31250 which is even, but the solution is 5 and5. So why isn\'t x=1 and y=31250/2=15625 a solution here? Let\'s check. 1^15625 *15625 +15625^1 *1. That would be 15625 +15625*1 = 31250. So 15625+15625=31250. Oh right. So (1,15625) would be a solution here. But the sample output gives (5,5). So the problem allows any valid pair. So in that case, there are multiple solutions, but the code can output any. So for n=31250, why isn\'t (1,15625) a valid solution? Because 15625 is <=31250. So why wasn\'t that the output in the sample? Oh, perhaps the sample is just one possible solution, and there are others. So the problem allows any valid pair.\n\nSo maybe the first step is to check if n is even. Then check if x=1, y= n/2. Similarly, x= n/2 and y=1 (since x and y are interchangeable here? Wait, no. Because x and y in the equation are in different positions. Let me see: x^y * y + y^x *x. So if x=1 and y=k, then the value is 1^k *k +k^1 *1= k +k =2k. So yes, even. So for even n, this could be a solution. But when x=1 and y=1, the equation is 1*1 +1*1=2. So for n=2, this is a solution.\n\nWait, but in the first sample input, n=3. 3 is odd, so 2y=3 has no integer solution, hence x=1 is not possible. So for even n, we can check if n is even, and if n/2 <=n (which it always is, as n>=1), then (1, n/2) is a solution. So maybe for even n, we can output 1 and n/2. But why in the fourth test case, the sample output is (5,5) instead of (1, 15625)? Because there are multiple possible solutions, and the problem allows any. But perhaps (1, n/2) is a valid solution for even n. However, perhaps for some n, even when it\'s even, the (1, n/2) pair is not the correct solution because when you compute the equation, it gives a different result. Wait, no. Because in the case x=1 and y=k, the equation is 2k. So 2k =n. So if n is even, k =n/2. So if we set x=1 and y =n/2, then the equation will hold. So for even n, this is a possible solution. So why isn\'t the sample input for 42\'s solution 1 and 21? Because 21*2 =42. Let\'s check: 1^21 *21 +21^1 *1 =21 +21 =42. So yes. So (1,21) is also a valid solution. But the sample output shows (2,3) and (3,2). So there are multiple solutions, but the code can output any. So why isn\'t the sample output for 42 showing (1,21) as a possible solution?\n\nAh, right. Because the problem states that x and y can be any pair that satisfies the equation, and the code can output any. So in that case, perhaps the intended solution is to check small x and y first, and when you find a solution, return that. But if you check (1, n/2) first, then for even n, you can immediately return that. However, perhaps for even n, there may be a case where (1, n/2) is a valid solution, but when n is even but n/2 is larger than n? No, since n is at least 1. Wait, for example, n=2: 1 and 1. Then 1^1 *1 +1^1 *1=2, which is correct. Wait, but 2 is even, and (1,1) would be a solution. But according to the earlier approach, (1, n/2) would be (1,1), which works. So for even n, (1, n/2) is a valid solution. So why isn\'t that the case in the sample input?\n\nWait, the third test case has n=42. 42 is even. So n/2=21. So (1,21) would be a solution. So why in the sample output, the solution is (2,3) and (3,2)? Because there are multiple solutions. So the code can output any. So perhaps the code can first check for x=1 and y =n/2, and if that works, output it. But why isn\'t that the case in the sample input? Because in the third test case, (1,21) is a valid solution, but the sample outputs (2,3). Hmm. Wait, perhaps I\'m missing something here.\n\nWait, wait. Let\'s compute for x=1 and y=21. The equation becomes:\n\n1^21 *21 + 21^1 *1 = 21 + 21 = 42. Yes. So that\'s correct. So (1,21) is a valid solution. So why the sample output is (2,3)? Because the problem allows any valid pair, and the sample shows one possible pair. So in that case, the code can output (1,21) for n=42, but the sample shows (2,3). So perhaps the code can check for x=1 and y= n/2 first, but maybe for some even n, this pair is invalid. Wait, but according to the equation, it\'s always valid for even n. Let me confirm for n=31250. The sample solution is 5 and 5. But according to x=1 and y=15625, that\'s also a solution. So why the sample doesn\'t output that? Because there are multiple solutions, and the code can output any. So in that case, perhaps the problem expects us to find any solution, but perhaps for some n, the solution with x=1 and y=n/2 is not feasible. For example, when n is even but y=n/2 exceeds the n. But wait, y has to be <=n. So for example, if n is even, then y =n/2. Since n >=2, then n/2 can be up to 5e8 when n is 1e9. So y is 5e8 which is <=1e9. So the condition holds. So for even n, (1, n/2) is a valid solution. So why the sample outputs for 42 and 31250 do not include that?\n\nAh, perhaps the problem has a mistake. Or maybe I\'m misunderstanding the problem. Let me re-read the problem statement.\n\nThe problem statement says, "Find any pair of integers (x,y) (1≤x,y≤n) such that x^y·y + y^x·x =n." So for even n, x=1 and y=n/2 is a solution. But in the sample input, the third test case is 42. So n is even. So why isn\'t the sample output (1,21) instead of (2,3)?\n\nWait, the sample input\'s third test case\'s output is 2 and 3. But according to the equation, x=1 and y=21 also works. So why isn\'t that the answer? Because the problem allows any pair, so (1,21) is a valid answer. But the sample output shows (2,3). So perhaps the problem has some constraints that I\'m missing. Or perhaps the problem expects x and y to be at least 2? No, the problem states 1 ≤x,y ≤n.\n\nWait, maybe I made a miscalculation. Let me compute x=1 and y=21:\n\n1^21 *21 = 1 *21 =21.\n\n21^1 *1 =21*1=21.\n\nTotal is 42. Yes, correct.\n\nSo why the sample output isn\'t (1,21)? Because the problem allows any solution, and the sample shows a different one. So the code can output (1,21) and it\'s correct. So in that case, the code can first check if n is even, and if so, output (1, n/2) and (n/2, 1). Wait, but the equation isn\'t symmetric. For example, if x=1 and y=k, then the value is 2k. So for the equation to hold, n must be 2k. But if x= k and y=1, then the equation becomes k^1 *1 +1^k *k =k +k =2k. So same result. So for even n, the pairs (1, n/2) and (n/2, 1) are valid. But wait, n/2 must be <=n, which is true. So for even n, there\'s a solution. But in the sample input, for n=7 (odd), output is -1. For n=3 (odd), output is -1.\n\nSo the first thing to check is whether n is even. If n is even, then (1, n/2) is a solution. However, looking at the sample input for n=7 (which is odd, so no solution). For n=42 (even), the sample solution is (2,3), but (1,21) is also a solution. So why isn\'t the code outputting (1,21) instead? Because the code is allowed to return any valid solution. So perhaps the code can first check for even n, and output (1, n/2), but perhaps there\'s a case where even n is such that x=1 and y= n/2 is not valid. Wait, but according to the equation, if n is even, then (1, n/2) must be a valid solution. Because substituting into the equation gives 2*(n/2) =n. So yes. So for even n, this is always a solution. So why the sample input for 42 doesn\'t show that solution? Because the sample output is just one possible solution. So the code can choose to output that pair.\n\nBut according to the sample input, for n=31250 (even), the code outputs (5,5). But according to the x=1 and y=15625, that\'s a valid solution. So why doesn\'t the sample output that? Because there\'s another solution, and the code can choose any. So the code can have multiple correct outputs. So for the problem, perhaps the intended solution is to find pairs where x and y are small. Because for large n, like 1e9, the (1, n/2) pair would have y=5e8, which is a very large number, but computing 1^5e8 is 1, multiplied by 5e8 gives 5e8. And 5e8^1 multiplied by 1 gives 5e8. So sum is 1e9. So for n=1e9, (1,5e8) is a valid solution.\n\nBut in this case, the code can output (1, n/2) for even n. But why then in the sample input for n=42, (1,21) is a valid solution but the sample shows (2,3). So perhaps the code can first check if (1, n/2) is a valid solution and output that. But why isn\'t that the case in the sample? Because the problem allows any solution, and the sample is just an example. So the code can output any solution. So the code can proceed by first checking if n is even, output (1, n/2) if that\'s within the constraints (which it is). But perhaps there\'s a problem when n is even but n/2 is larger than n. Wait, no. Because n/2 is at most n (when n=1, but n=1 is odd. For even n=2, n/2 is 1, which is <=2. So y is always <=n.\n\nWait, the constraints are 1<=x,y <=n. So for even n, x=1 and y= n/2. But n/2 can\'t exceed n. For example, if n=4, y=2. So yes, 2 <=4. So in all cases where n is even, x=1 and y= n/2 is a valid solution. So why the sample for n=42 doesn\'t show that? Because the problem allows any solution, and the sample is just one possible solution.\n\nBut then why in the sample input for n=31250, which is even, the solution is (5,5) instead of (1,15625). Because (5,5) is also a valid solution, and perhaps the code can find that first.\n\nSo perhaps the approach is to check all possible pairs (x, y) where x and y are small (like up to 20) and see if any of them satisfy the equation, and if not, check if n is even and return (1, n/2). Because for large x and y, the equation\'s value could be very big, but n is up to 1e9, so small x and y could also generate that value.\n\nSo the strategy could be:\n\nFor each test case:\n\n1. Check if n is even. If yes, check if (1, n/2) is a valid solution. If yes, output that.\n\nBut wait, since n is even, (1, n/2) is automatically a valid solution. So outputting that would solve the case. But why the sample input for 42 has a solution (2,3) but according to this approach, (1,21) would be output. So in that case, the code would output (1,21), but the sample shows (2,3). But according to the problem statement, any valid solution is acceptable. So perhaps the code can output (1,21) and it\'s correct.\n\nBut the sample shows (2,3). So perhaps the code\'s approach of checking for x=1 and y= n/2 is not sufficient for all even n. Because maybe for some even n, the (1, n/2) pair would have y >n. But that\'s impossible. Because y= n/2. For example, n=42, y=21. 21<=42. So it\'s valid.\n\nBut according to the sample, there exists a solution (2,3) which is also valid. So the code can output either. So why isn\'t the sample showing (1,21) as a possible solution? Because the problem allows any solution.\n\nBut the problem\'s sample output shows (2,3) for n=42. So perhaps the intended solution is to find pairs where x and y are small, but the problem allows any pair. So the code can find any solution.\n\nSo perhaps the code\'s approach is to first check small x and y (like up to 20) and if any pair is found, return it. If not, then check if n is even, return (1, n/2). Otherwise, return -1.\n\nBut why check small x and y first? Because for even n, there\'s always a solution (x=1, y=n/2). But the sample input for n=31250 is even and the solution is (5,5). So why not output (1,15625)? Because the code is allowed to output any solution. But perhaps there are multiple solutions, and the code can find any. So perhaps the code should first check for small x and y, which may be faster than handling even n\'s first.\n\nSo let\'s think about how to approach this. For each test case:\n\nCheck possible x and y pairs where x and y are small (like up to 30). Because for larger x and y, the value could become very large quickly. For example, x=2, y=30: 2^30 is a huge number, multiplied by 30 would be way beyond 1e9. So even for x=2 and y=30, the value is 2^30*30 which is 3*10^10, which is larger than 1e9. So for n up to 1e9, perhaps the possible solutions with x and y greater than 30 would not exist. So checking x and y up to 30 would cover all possible cases except for when x or y is 1.\n\nWait, but when x=1 and y is large, the equation becomes 2y, which is up to 2n. So for example, if n is 1e9, then y=5e8. So (1,5e8) is a valid solution. So in that case, even if x and y are 5e8, which is a large number, the code can output (1,5e8). But how can the code check that efficiently?\n\nBut for n up to 1e9, when n is even, x=1 and y= n/2 is a valid solution. So for even n, the code can output (1, n/2) immediately. So perhaps the code can first check if n is even. If yes, then output (1, n/2). But then why in the sample input, n=31250 (even) is output as (5,5) instead of (1, 15625). Because (5,5) is also a valid solution. So the code can choose any solution. So perhaps the code should first check for small x and y, and if found, output that. Otherwise, check if n is even and output (1, n/2). Otherwise, output -1.\n\nSo the approach could be:\n\nFor each test case:\n\n1. Check for x in 1 to some limit (like 30). For each x, check for y in 1 to some limit (like 30). Compute x^y * y + y^x *x. If this equals n, then output (x,y) or (y,x) if applicable.\n\n2. If no such pair is found, check if n is even. If yes, then output (1, n/2) if n/2 <=n.\n\n3. Else, output -1.\n\nBut wait, step 1 could miss some pairs where x or y is larger than 30. But for those pairs, the value could be too large. For example, x=5 and y=5 gives 5^5 *5 +5^5 *5 = 2 * 3125 *5= 31250, which is exactly the fourth test case. So in that case, x and y are 5, which is within 30. So step 1 would find that.\n\nBut if a solution exists for x and y up to 30, step 1 will find it. Otherwise, check if n is even.\n\nBut why in the third test case (n=42), the code would find (2,3) in step 1. Then output that, instead of (1,21).\n\nBut according to the problem statement, any solution is acceptable. So in that case, the code can return (2,3) which is found in step 1, and that\'s correct.\n\nSo the code should first check for x and y in small ranges, then check for even n.\n\nThis approach can handle the sample test cases.\n\nBut how to determine the upper limit for x and y in step 1. Let\'s see.\n\nLet\'s see for x and y up to 30. Let\'s compute x^y * y + y^x *x.\n\nFor x=2, y=3: 8*3 +9*2=24+18=42.\n\nFor x=5, y=5: 3125*5 +3125*5= 31250.\n\nFor x=3, y=13: let\'s compute 3^13 *13 +13^3 *3.\n\n3^13 is 1594323. Multiply by 13 gives 20726199.\n\n13^3 is 2197. Multiply by 3 gives 6591.\n\nSum is 20726199 +6591= 20732790, which matches the fifth test case.\n\nSo x=3 and y=13. Both are within 30. So checking up to 30 would cover this case.\n\nSo the code can check x and y up to 30. But why 30? Because 3^20 is already 3,486,784,401 which when multiplied by 20 would be 6.97e10, which is way larger than 1e9. So for x and y up to 30, the values would quickly exceed 1e9, making the sum not possible. So perhaps checking up to 20 or 30 is sufficient.\n\nBut how to find the minimal x and y pairs.\n\nSo the code can iterate x from 1 to 30, and for each x, iterate y from 1 to 30, compute the sum. If it equals n, output (x,y). But also check (y,x) since x and y are interchangeable in the equation.\n\nWait, no. Because x and y are not interchangeable. For example, x=2 and y=3 is different from x=3 and y=2. Let\'s see:\n\nFor (2,3): 2^3 *3 +3^2*2 = 8*3 +9*2 =24+18=42.\n\nFor (3,2):3^2 *2 +2^3 *3=9*2 +8*3=18+24=42. So the sum is the same. So if (x,y) is a solution, then (y,x) is also a solution.\n\nSo in the code, when x and y are iterated from 1 to 30, but to avoid redundant checks, perhaps we can check x <= y, and then check (x,y) and (y,x). But maybe it\'s easier to check all possible pairs, even if some are redundant.\n\nBut for code efficiency, checking all pairs up to 30 each would be manageable. Since 30*30=900, and for 1e4 test cases, 9e6 operations. Which is acceptable.\n\nSo the code can loop x from 1 to 30, and y from 1 to 30. For each pair (x,y), compute the value. If equals n, output. Once any solution is found, return.\n\nIf no solution is found in the loops, check if n is even. If even, return (1, n/2). Else return -1.\n\nBut wait, the code should check for x and y up to n. But n can be up to 1e9, so checking up to 1e9 is impossible. Hence, the code must find an efficient way to check possible x and y pairs that can generate the sum up to 1e9.\n\nBut when x and y are both 30, 30^30 is way larger than 1e9. So even for x=20, y=20, the sum would be 20^20 *20 +20^20 *20 = 2*20^21, which is way beyond 1e9. So checking up to x and y as 30 is sufficient.\n\nSo the code can loop x from 1 to 30, and y from 1 to 30. For each (x, y), compute the sum. If it equals n, output.\n\nBut there\'s another case where x=1 and y is large. For example, n=2, which is even, and (1,1) is a solution. But according to the

In [10]:
def formatting_prompts_func(examples):
    instructions = examples["problem"]
    responses = examples["generation"]
    texts = []
    for instruction, response in zip(instructions, responses):
        # Format as a standard conversation dictionary
        messages = [
            {"role": "user", "content": instruction},
            {"role": "assistant", "content": response},
        ]
        # Apply the chat template and get the raw string
        text = tokenizer.apply_chat_template(messages, tokenize = False, add_generation_prompt = False)
        texts.append(text)
    return texts

<a name="Train"></a>
### Train the model
Now let's train our model. We do 60 steps to speed things up, but you can set `num_train_epochs=1` for a full run, and turn off `max_steps=None`. We also support `DPOTrainer` and `GRPOTrainer` for reinforcement learning!!

In [14]:
from trl import SFTTrainer, SFTConfig
from transformers import TrainingArguments
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = train_ds,
    max_seq_length = max_seq_length,
    formatting_func = formatting_prompts_func,
    packing = False, # Can make training 5x faster for short sequences.
    args = SFTConfig(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 60,
        learning_rate = 2e-4,
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.001,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", # Use TrackIO/WandB etc
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=8):   0%|          | 0/1600 [00:00<?, ? examples/s]

🦥 Unsloth: Padding-free auto-enabled, enabling faster training.

In [20]:
# @title Show current memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

GPU = Tesla T4. Max memory = 14.563 GB.
12.816 GB of memory reserved.

In [18]:
torch.cuda.empty_cache()

In [53]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 1,600 | Num Epochs = 1 | Total steps = 60
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 29,933,568 of 3,115,872,256 (0.96% trained)

In [ ]:
# @title Show final memory and time stats
used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory / max_memory * 100, 3)
lora_percentage = round(used_memory_for_lora / max_memory * 100, 3)
print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(
    f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training."
)
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

462.3942 seconds used for training.
7.71 minutes used for training.
Peak reserved memory = 7.893 GB.
Peak reserved memory for training = 2.129 GB.
Peak reserved memory % of max memory = 53.519 %.
Peak reserved memory for training % of max memory = 14.436 %.

<a name="Inference"></a>
### Inference
Let's run the model! You can change the instruction and input - leave the output blank!

In [12]:
example_problem = """A tech company, "DataGoSlow," produces high-performance memory modules. They sell these modules in 'n' different retail outlets. Each outlet sells the modules at a unique price, represented by 'xi' dollars.

A large data center plans to purchase these memory modules over 'q' consecutive procurement cycles. For each cycle, the data center has a budget constraint 'mi' dollars. They want to know how many outlets sell the memory modules at a price *strictly less than* their budget.

**Constraints:**

* Time limit per test: 2.0 seconds
* Memory limit per test: 256.0 megabytes

**Input Format:**

* The first line of the input contains a single integer 'n' (1 ≤ n ≤ 100 000) — the number of retail outlets.
* The second line contains 'n' integers 'xi' (1 ≤ xi ≤ 100 000) — prices of the memory modules in each outlet.
* The third line contains a single integer 'q' (1 ≤ q ≤ 100 000) — the number of procurement cycles.
* Then follow 'q' lines, each containing one integer 'mi' (1 ≤ mi ≤ 109) — the budget for the i-th procurement cycle.

**Output Format:**

* Print 'q' integers. The i-th of them should be equal to the number of outlets where the memory modules can be purchased at a price *strictly less than* the budget for the i-th cycle.

**Example:**

```input
5
3 10 8 6 11
4
1
10
3
11"""

FastLanguageModel.for_inference(model) # Enable native 2x faster inference
inputs = tokenizer([example_problem], return_tensors = "pt").to("cuda")

outputs = model.generate(**inputs, max_new_tokens = 64, use_cache = True)
tokenizer.batch_decode(outputs)

['A tech company, "DataGoSlow," produces high-performance memory modules. They sell these modules in \'n\' different retail outlets. Each outlet sells the modules at a unique price, represented by \'xi\' dollars.\n\nA large data center plans to purchase these memory modules over \'q\' consecutive procurement cycles. For each cycle, the data center has a budget constraint \'mi\' dollars. They want to know how many outlets sell the memory modules at a price *strictly less than* their budget.\n\n**Constraints:**\n\n* Time limit per test: 2.0 seconds\n* Memory limit per test: 256.0 megabytes\n\n**Input Format:**\n\n* The first line of the input contains a single integer \'n\' (1 ≤ n ≤ 100 000) — the number of retail outlets.\n* The second line contains \'n\' integers \'xi\' (1 ≤ xi ≤ 100 000) — prices of the memory modules in each outlet.\n* The third line contains a single integer \'q\' (1 ≤ q ≤ 100 000) — the number of procurement cycles.\n* Then follow \'q\' lines, each containing one integer \'mi\' (1 ≤ mi ≤ 109) — the budget for the i-th procurement cycle.\n\n**Output Format:**\n\n* Print \'q\' integers. The i-th of them should be equal to the number of outlets where the memory modules can be purchased at a price *strictly less than* the budget for the i-th cycle.\n\n**Example:**\n\n```input\n5\n3 10 8 6 11\n4\n1\n10\n3\n11\n```\n\n```output\n0\n2\n3\n0\n```\n\n**Note:**\n\nIn the first and fourth cases, there are no such outlets.\n\nIn the second case, the first and third outlets have prices less than 10.\n\nIn the third case, all three outlets have prices less than ']

 You can also use a `TextStreamer` for continuous inference - so you can see the generation token by token, instead of waiting the whole time!

In [ ]:
FastLanguageModel.for_inference(model) # Enable native 2x faster inference

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer)
_ = model.generate(**inputs, streamer = text_streamer, max_new_tokens = 128)

Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
Continue the fibonnaci sequence.

### Input:
1, 1, 2, 3, 5, 8

### Response:
13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811,

In [54]:
model

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Qwen2ForCausalLM(
      (model): Qwen2Model(
        (embed_tokens): Embedding(151936, 2048, padding_idx=151665)
        (layers): ModuleList(
          (0-35): 36 x Qwen2DecoderLayer(
            (self_attn): Qwen2Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=2048, out_features=2048, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2048, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=2048, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=2048, out_features=256, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2048, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=256, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=2048, out_features=256, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2048, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=256, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=2048, out_features=2048, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2048, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=2048, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen2MLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=2048, out_features=11008, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2048, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=11008, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=2048, out_features=11008, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2048, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=11008, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=11008, out_features=2048, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=11008, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=2048, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLU()
            )
            (input_layernorm): Qwen2RMSNorm((2048,), eps=1e-06)
            (post_attention_layernorm): Qwen2RMSNorm((2048,), eps=1e-06)
          )
        )
        (norm): Qwen2RMSNorm((2048,), eps=1e-06)
        (rotary_emb): LlamaRotaryEmbedding()
      )
      (lm_head): Linear(in_features=2048, out_features=151936, bias=False)
    )
  )
)

<a name="Save"></a>
### Saving, loading finetuned models
To save the final model as LoRA adapters, either use Hugging Face's `push_to_hub` for an online save or `save_pretrained` for a local save.

**[NOTE]** This ONLY saves the LoRA adapters, and not the full model. To save to 16bit or GGUF, scroll down!

In [55]:
model.save_pretrained("codeforces_cot_finetune_lora")  # Local saving
tokenizer.save_pretrained("codeforces_cot_finetune_lora")
# model.push_to_hub("your_name/codeforces_cot_finetune_lora", token = "YOUR_HF_TOKEN") # Online saving
# tokenizer.push_to_hub("your_name/codeforces_cot_finetune_lora", token = "YOUR_HF_TOKEN") # Online saving

('codeforces_cot_finetune_lora/tokenizer_config.json',
 'codeforces_cot_finetune_lora/special_tokens_map.json',
 'codeforces_cot_finetune_lora/chat_template.jinja',
 'codeforces_cot_finetune_lora/vocab.json',
 'codeforces_cot_finetune_lora/merges.txt',
 'codeforces_cot_finetune_lora/added_tokens.json',
 'codeforces_cot_finetune_lora/tokenizer.json')

Now if you want to load the LoRA adapters we just saved for inference, set `False` to `True`:

In [ ]:
if False:
    from unsloth import FastLanguageModel
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = "codeforces_cot_finetune_lora", # YOUR MODEL YOU USED FOR TRAINING
        max_seq_length = max_seq_length,
        dtype = dtype,
        load_in_4bit = load_in_4bit,
    )
    FastLanguageModel.for_inference(model) # Enable native 2x faster inference

# alpaca_prompt = You MUST copy from above!

inputs = tokenizer(
[
    alpaca_prompt.format(
        "What is a famous tall tower in Paris?", # instruction
        "", # input
        "", # output - leave this blank for generation!
    )
], return_tensors = "pt").to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer)
_ = model.generate(**inputs, streamer = text_streamer, max_new_tokens = 128)

Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
What is a famous tall tower in Paris?

### Input:


### Response:
One of the most famous tall towers in Paris is the Eiffel Tower. It was built by Gustave Eiffel in 1889 and stands at a height of 324 meters (1,063 feet). It is a symbol of Paris and one of the most recognizable structures in the world.<|endoftext|>

In [57]:
!zip -r codeforces_cot_finetune_lora.zip /kaggle/working/codeforces_cot_finetune_lora

  adding: kaggle/working/codeforces_cot_finetune_lora/ (stored 0%)
  adding: kaggle/working/codeforces_cot_finetune_lora/adapter_config.json (deflated 57%)
  adding: kaggle/working/codeforces_cot_finetune_lora/tokenizer.json (deflated 81%)
  adding: kaggle/working/codeforces_cot_finetune_lora/tokenizer_config.json (deflated 89%)
  adding: kaggle/working/codeforces_cot_finetune_lora/added_tokens.json (deflated 65%)
  adding: kaggle/working/codeforces_cot_finetune_lora/vocab.json (deflated 61%)
  adding: kaggle/working/codeforces_cot_finetune_lora/special_tokens_map.json (deflated 67%)
  adding: kaggle/working/codeforces_cot_finetune_lora/README.md (deflated 65%)
  adding: kaggle/working/codeforces_cot_finetune_lora/chat_template.jinja (deflated 71%)
  adding: kaggle/working/codeforces_cot_finetune_lora/adapter_model.safetensors (deflated 8%)
  adding: kaggle/working/codeforces_cot_finetune_lora/merges.txt (deflated 57%)

You can also use Hugging Face's `AutoPeftModelForCausalLM`. Only use this if you do not have `unsloth` installed. It can be hopelessly slow, since `4bit` model downloading is not supported, and Unsloth's **inference is 2x faster**.

In [ ]:
if False:
    # I highly do NOT suggest - use Unsloth if possible
    from peft import AutoPeftModelForCausalLM
    from transformers import AutoTokenizer
    model = AutoPeftModelForCausalLM.from_pretrained(
        "codeforces_cot_finetune_lora", # YOUR MODEL YOU USED FOR TRAINING
        load_in_4bit = load_in_4bit,
    )
    tokenizer = AutoTokenizer.from_pretrained("codeforces_cot_finetune_lora")

### Saving to float16 for VLLM

We also support saving to `float16` directly. Select `merged_16bit` for float16 or `merged_4bit` for int4. We also allow `lora` adapters as a fallback. Use `push_to_hub_merged` to upload to your Hugging Face account! You can go to https://huggingface.co/settings/tokens for your personal tokens. See [our docs](https://unsloth.ai/docs/basics/inference-and-deployment) for more deployment options.

In [ ]:
# Merge to 16bit
if False: model.save_pretrained_merged("codeforces_cot_finetune_16bit", tokenizer, save_method = "merged_16bit",)
if False: model.push_to_hub_merged("HF_USERNAME/codeforces_cot_finetune_16bit", tokenizer, save_method = "merged_16bit", token = "YOUR_HF_TOKEN")

# Merge to 4bit
if False: model.save_pretrained_merged("codeforces_cot_finetune_4bit", tokenizer, save_method = "merged_4bit",)
if False: model.push_to_hub_merged("HF_USERNAME/codeforces_cot_finetune_4bit", tokenizer, save_method = "merged_4bit", token = "YOUR_HF_TOKEN")

# Just LoRA adapters
if False:
    model.save_pretrained("codeforces_cot_finetune_lora")
    tokenizer.save_pretrained("codeforces_cot_finetune_lora")
if False:
    model.push_to_hub("HF_USERNAME/codeforces_cot_finetune_lora", token = "YOUR_HF_TOKEN")
    tokenizer.push_to_hub("HF_USERNAME/codeforces_cot_finetune_lora", token = "YOUR_HF_TOKEN")

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now! We clone `llama.cpp` and we default save it to `q8_0`. We allow all methods like `q4_k_m`. Use `save_pretrained_gguf` for local saving and `push_to_hub_gguf` for uploading to HF.

Some supported quant methods (full list on our [docs page](https://unsloth.ai/docs/basics/inference-and-deployment/saving-to-gguf)):
* `q8_0` - Fast conversion. High resource use, but generally acceptable.
* `q4_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K.
* `q5_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K.

[**NEW**] To finetune and auto export to Ollama, try our [Ollama notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)

In [ ]:
# Save to 8bit Q8_0
if False: model.save_pretrained_gguf("codeforces_cot_finetune", tokenizer,)
# Remember to go to https://huggingface.co/settings/tokens for a token!
# And change hf to your username!
if False: model.push_to_hub_gguf("HF_USERNAME/codeforces_cot_finetune", tokenizer, token = "YOUR_HF_TOKEN")

# Save to 16bit GGUF
if False: model.save_pretrained_gguf("codeforces_cot_finetune", tokenizer, quantization_method = "f16")
if False: model.push_to_hub_gguf("HF_USERNAME/codeforces_cot_finetune", tokenizer, quantization_method = "f16", token = "YOUR_HF_TOKEN")

# Save to q4_k_m GGUF
if False: model.save_pretrained_gguf("codeforces_cot_finetune", tokenizer, quantization_method = "q4_k_m")
if False: model.push_to_hub_gguf("HF_USERNAME/codeforces_cot_finetune", tokenizer, quantization_method = "q4_k_m", token = "YOUR_HF_TOKEN")

# Save to multiple GGUF options - much faster if you want multiple!
if False:
    model.push_to_hub_gguf(
        "HF_USERNAME/codeforces_cot_finetune", # Change hf to your username!
        tokenizer,
        quantization_method = ["q4_k_m", "q8_0", "q5_k_m",],
        token = "YOUR_HF_TOKEN", # Get a token at https://huggingface.co/settings/tokens
    )

Now, use the `codeforces_cot_finetune.Q8_0.gguf` file or `codeforces_cot_finetune.Q4_K_M.gguf` file in llama.cpp.

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other resources:
1. Train your own reasoning model - Llama GRPO notebook [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.1_(8B)-GRPO.ipynb)
2. Saving finetunes to Ollama. [Free notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)
3. Llama 3.2 Vision finetuning - Radiography use case. [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(11B)-Vision.ipynb)
4. See notebooks for DPO, ORPO, Continued pretraining, conversational finetuning and more on our [documentation](https://unsloth.ai/docs/get-started/unsloth-notebooks)!

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️
</div>

  This notebook and all Unsloth notebooks are licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).